project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise1"
        href: "./Hands-on_Ex/Hands-on_Ex01/Hands_On_Ex01.html"
      - text: "Hands-on Exercise2"
        href: "./Hands-on_Ex/Hands-on_Ex02/Hands_On_Ex02.html"
      - text: "Hands-on Exercise3"
        href: "./Hands-on_Ex/Hands-on_Ex03/Hands_On_Ex03.html"
      - text: "Hands-on Exercise4"
        href: "./Hands-on_Ex/Hands-on_Ex04/Hands_On_Ex04.html"
      - text: "Hands-on Exercise5"
        href: "./Hands-on_Ex/Hands-on_Ex05/Hands_On_Ex05.html"
        
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 3a"
        href: "./In-Class Exercise/In-Class Exercise 3/In_Class_Ex03a.html"
    - text: "Take-home exercise"
      menu:
      - text: "Take-Home Exercise1"
        href: "./Take Home Exercise/Take Home Exercise 1/Take_Home_Ex01.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: quartz
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual