project:
  type: website

website:
  title: "ISSS626-wp"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise3"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
    - text: "In-class Exercise"
    - text: "Take-home exercise"
      menu:
      - text: "Take-Home Exercise1"
        href: "Assignment1/Take-Home_Exercise_1.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual