---
title: "In-class Exercise 7"
author: "Wong Zi Sheng"
date: "Octover 18, 2025"
date-modified: "last-modified"
---

```{r}
setwd('/Users/zishengwong/R Coding/ISSS626 Geospatial Analytics/In-Class Exercise/In-class Exercise 7')
```

```{r}
pacman::p_load(olsrr, ggstatsplot, ggpubr, 
               sf, spdep, GWmodel, tmap,
               tidyverse, gtsummary, performance,
               see, sfdep)
```

```{r}
condo_resale <- read_csv("./data/aspatial/Condo_resale_2015.csv")
```

```{r}
mpsz <- read_rds("./data/rds/mpsz_cl.rds")
```

```{r}
condo_resale_sf <- st_as_sf(
  condo_resale,
  coords = c("LONGITUDE", "LATITUDE"), # replace with your actual column names
  crs = 4326                           # WGS84 (standard GPS coordinate system)
)
```

```{r}
ggcorrmat(condo_resale[, 5:23])
```

Building a hedonic pricing model

```{r}
condo_mlr <- lm(formula = SELLING_PRICE ~ AREA_SQM + 
                  AGE   + PROX_CBD + PROX_CHILDCARE + 
                  PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
                  PROX_HAWKER_MARKET    + PROX_KINDERGARTEN + 
                  PROX_MRT  + PROX_PARK + PROX_PRIMARY_SCH + 
                  PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + 
                  PROX_SUPERMARKET + PROX_BUS_STOP + 
                  NO_Of_UNITS + FAMILY_FRIENDLY + 
                  FREEHOLD + LEASEHOLD_99YR, 
                data=condo_resale_sf)
summary(condo_mlr)
```

Generating tidy linear regression report

```{r}
ols_regress(condo_mlr)
```

```{r}
ols_vif_tol(condo_mlr)
```

```{r}
condo_fw_mlr <- ols_step_forward_p(
  condo_mlr,
  p_val = 0.05,
  details = FALSE)
```

```{r}
plot(condo_fw_mlr)
```

Visualising parameters

```{r}
ggcoefstats(condo_mlr,
            sort = "ascending")
```

Test non-linearity

```{r}
ols_plot_resid_fit(condo_fw_mlr$model)
```

Test normality\

```{r}
ols_plot_resid_hist(condo_fw_mlr$model)
```

```{r}
ols_test_normality(condo_fw_mlr$model)
```

Test Spatial Autocorrelation

```{r}
mlr_output <- as.data.frame(condo_fw_mlr$model$residuals) %>%
  rename(`FW_MLR_RES` = `condo_fw_mlr$model$residuals`)
```

```{r}
condo_resale_sf <- cbind(condo_resale_sf, 
                        mlr_output$FW_MLR_RES) %>%
  rename(`MLR_RES` = `mlr_output.FW_MLR_RES`)
```

```{r}
library(tmap)

tmap_mode("view")

tm_shape(mpsz) +
  tm_polygons(alpha = 0.4) +
tm_shape(condo_resale_sf) +  
  tm_dots(col = "MLR_RES",
          alpha = 0.6,
          style = "quantile")

tmap_mode("plot")
```

Spatial stationary test

```{r}
condo_resale_sf <- condo_resale_sf %>%
  mutate(nb = st_knn(geometry, k=6,
                     longlat = FALSE),
         wt = st_weights(nb,
                         style = "W"),
         .before = 1)
```

```{r}
global_moran_perm(condo_resale_sf$MLR_RES, 
                  condo_resale_sf$nb, 
                  condo_resale_sf$wt, 
                  alternative = "two.sided", 
                  nsim = 99)
```
